//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrukoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETune
    {
        public int Id { get; set; }
        public string Rbt_Name { get; set; }
        public string Rbt_Code { get; set; }
        public string Artiste { get; set; }
    }
}
