//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrukoData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tune
    {
        public int Id { get; set; }
        public string Names { get; set; }
        public string mCode { get; set; }
        public string wCode { get; set; }
        public string Artist { get; set; }
    }
}
